# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="philips"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git z)

source $ZSH/oh-my-zsh.sh

# User configuration


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

##############################################################

# Homebrew
#export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="/usr/local/bin:$PATH"
 export MANPATH="/usr/local/man:$MANPATH"

# ARM related
export PATH=/work/bin:$PATH

# ARM related
export PATH=~/bin:$PATH

alias use_abs='
abs_dir="/arm/devsys-tools/abs"
if [ -d $abs_dir ]; then
    export PATH=/arm/devsys-tools/abs:/arm/devsys-tools/abs/libexec:$PATH;
    export WORK_USER=tholuf01
    alias linfo="binfo server=localhost";
else
    echo "no mounts"
fi'

alias use_abslocal='export PATH=/work/abs_local/bin:/work/abs_local/libexec:$PATH;
export WORK_USER=tholuf01;
alias linfo="binfo server=localhost"'

alias use_doxygen='eval `setup_wh_comp DsysTools:doxygen:1.8.5:@ --deps-via cloud`;
eval `setup_wh_comp DsysTools:doxygenfilter:1.10:@ --deps-via cloud`'

alias use_condor='export CONDOR_CONFIG=/work/condor_config;
eval `setup_wh_comp OpenSource:Condor:7.8.1:5 --deps-via cloud`'

alias use_perl='eval `setup_wh_comp DsysTools:perl:5.14.2:1:threaded=undefine`'
alias use_perlt='eval `setup_wh_comp DsysTools:perl:5.14.2:1:threaded=define`'


# init plenv
export PATH="$HOME/.plenv/bin:$PATH"
eval "$(plenv init -)"

# init pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Stop homebrew searches being rate limited (as much)
export HOMEBREW_GITHUB_API_TOKEN=

#To enable shims and autocompletion add to your profile:
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

setopt interactivecomments
